<?php

$accredited_qualifications = [

    ["accredited_institution_id"=>"7","professional_qualification_id"=>"1","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"4","professional_qualification_id"=>"1","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"11","professional_qualification_id"=>"1","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"1","professional_qualification_id"=>"1","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"5","professional_qualification_id"=>"1","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"12","professional_qualification_id"=>"2","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"12","professional_qualification_id"=>"3","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"6","professional_qualification_id"=>"5","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"14","professional_qualification_id"=>"8","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"15","professional_qualification_id"=>"10","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"15","professional_qualification_id"=>"7","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"15","professional_qualification_id"=>"11","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"16","professional_qualification_id"=>"4","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"16","professional_qualification_id"=>"5","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"16","professional_qualification_id"=>"43","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"9","professional_qualification_id"=>"12","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"9","professional_qualification_id"=>"13","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"9","professional_qualification_id"=>"14","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"7","professional_qualification_id"=>"16","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"4","professional_qualification_id"=>"16","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"1","professional_qualification_id"=>"16","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"5","professional_qualification_id"=>"16","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"12","professional_qualification_id"=>"17","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"9","professional_qualification_id"=>"19","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"10","professional_qualification_id"=>"20","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"10","professional_qualification_id"=>"21","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"12","professional_qualification_id"=>"22","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"8","professional_qualification_id"=>"23","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"12","professional_qualification_id"=>"24","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"8","professional_qualification_id"=>"25","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"12","professional_qualification_id"=>"26","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"16","professional_qualification_id"=>"27","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"16","professional_qualification_id"=>"28","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"6","professional_qualification_id"=>"30","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"6","professional_qualification_id"=>"31","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"13","professional_qualification_id"=>"30","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"2","professional_qualification_id"=>"32","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"12","professional_qualification_id"=>"33","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"12","professional_qualification_id"=>"34","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"12","professional_qualification_id"=>"35","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"10","professional_qualification_id"=>"36","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"10","professional_qualification_id"=>"37","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"10","professional_qualification_id"=>"38","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"18","professional_qualification_id"=>"39","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"3","professional_qualification_id"=>"40","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"3","professional_qualification_id"=>"41","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"18","professional_qualification_id"=>"41","created_at"=>now(),"updated_at"=>now()],
    ["accredited_institution_id"=>"10","professional_qualification_id"=>"42","created_at"=>now(),"updated_at"=>now()]
];

return $accredited_qualifications;
