@extends('layouts.admin')

@section('content')
    <div class="container"><div class="v-card v-sheet theme--light"><div class="v-card__title blue lighten-4"><div>Required Company Documents</div> <div class="spacer"></div> <div class="red--text">Outstanding  0</div></div> <div class="v-card__text"><div role="list" class="v-list v-sheet theme--light v-list--two-line"><div><div tabindex="-1" role="listitem" class="v-list-item theme--light"><div class="v-list-item__content"><div class="v-list-item__title">Certificate of Incorporation</div> <div class="v-list-item__subtitle"><div class="green--text">Uploaded</div></div></div> <div class="v-list-item__action"><div><div><button type="button" class="blue white--text v-btn v-btn--depressed v-btn--flat v-btn--outlined v-btn--rounded theme--light v-size--default"><span class="v-btn__content">
                                    Edit
                            </span></button></div> <div role="dialog" class="v-dialog__container"><!----></div> <div role="dialog" class="v-dialog__container" height="50"><!----></div> <div class="v-snack v-snack--has-background v-snack--top" style="padding-bottom: 0px; padding-top: 123px;"><div class="v-snack__wrapper v-sheet theme--dark" style="display: none;"><div role="status" aria-live="polite" class="v-snack__content">

                                            </div><div class="v-snack__action "></div></div></div></div></div></div> <hr role="separator" aria-orientation="horizontal" class="v-divider theme--light"></div><div><div tabindex="-1" role="listitem" class="v-list-item theme--light"><div class="v-list-item__content"><div class="v-list-item__title">CR14</div> <div class="v-list-item__subtitle"><div class="green--text">Uploaded</div></div></div> <div class="v-list-item__action"><div><div><button type="button" class="blue white--text v-btn v-btn--depressed v-btn--flat v-btn--outlined v-btn--rounded theme--light v-size--default"><span class="v-btn__content">
                                    Edit
                            </span></button></div> <div role="dialog" class="v-dialog__container"><!----></div> <div role="dialog" class="v-dialog__container" height="50"><!----></div> <div class="v-snack v-snack--has-background v-snack--top" style="padding-bottom: 0px; padding-top: 123px;"><div class="v-snack__wrapper v-sheet theme--dark" style="display: none;"><div role="status" aria-live="polite" class="v-snack__content">

                                            </div><div class="v-snack__action "></div></div></div></div></div></div> <hr role="separator" aria-orientation="horizontal" class="v-divider theme--light"></div><div><div tabindex="-1" role="listitem" class="v-list-item theme--light"><div class="v-list-item__content"><div class="v-list-item__title">CR6</div> <div class="v-list-item__subtitle"><div class="green--text">Uploaded</div></div></div> <div class="v-list-item__action"><div><div><button type="button" class="blue white--text v-btn v-btn--depressed v-btn--flat v-btn--outlined v-btn--rounded theme--light v-size--default"><span class="v-btn__content">
                                    Edit
                            </span></button></div> <div role="dialog" class="v-dialog__container"><!----></div> <div role="dialog" class="v-dialog__container" height="50"><!----></div> <div class="v-snack v-snack--has-background v-snack--top" style="padding-bottom: 0px; padding-top: 123px;"><div class="v-snack__wrapper v-sheet theme--dark" style="display: none;"><div role="status" aria-live="polite" class="v-snack__content">

                                            </div><div class="v-snack__action "></div></div></div></div></div></div> <hr role="separator" aria-orientation="horizontal" class="v-divider theme--light"></div><div><div tabindex="-1" role="listitem" class="v-list-item theme--light"><div class="v-list-item__content"><div class="v-list-item__title">Articles and Memorandum of Association</div> <div class="v-list-item__subtitle"><div class="green--text">Uploaded</div></div></div> <div class="v-list-item__action"><div><div><button type="button" class="blue white--text v-btn v-btn--depressed v-btn--flat v-btn--outlined v-btn--rounded theme--light v-size--default"><span class="v-btn__content">
                                    Edit
                            </span></button></div> <div role="dialog" class="v-dialog__container"><!----></div> <div role="dialog" class="v-dialog__container" height="50"><!----></div> <div class="v-snack v-snack--has-background v-snack--top" style="padding-bottom: 0px; padding-top: 123px;"><div class="v-snack__wrapper v-sheet theme--dark" style="display: none;"><div role="status" aria-live="polite" class="v-snack__content">

                                            </div><div class="v-snack__action "></div></div></div></div></div></div> <hr role="separator" aria-orientation="horizontal" class="v-divider theme--light"></div><div><div tabindex="-1" role="listitem" class="v-list-item theme--light"><div class="v-list-item__content"><div class="v-list-item__title">Company Profile</div> <div class="v-list-item__subtitle"><div class="green--text">Uploaded</div></div></div> <div class="v-list-item__action"><div><div><button type="button" class="blue white--text v-btn v-btn--depressed v-btn--flat v-btn--outlined v-btn--rounded theme--light v-size--default"><span class="v-btn__content">
                                    Edit
                            </span></button></div> <div role="dialog" class="v-dialog__container"><!----></div> <div role="dialog" class="v-dialog__container" height="50"><!----></div> <div class="v-snack v-snack--has-background v-snack--top" style="padding-bottom: 0px; padding-top: 123px;"><div class="v-snack__wrapper v-sheet theme--dark" style="display: none;"><div role="status" aria-live="polite" class="v-snack__content">

                                            </div><div class="v-snack__action "></div></div></div></div></div></div> <hr role="separator" aria-orientation="horizontal" class="v-divider theme--light"></div></div></div></div> <div role="dialog" class="v-dialog__container"></div> <div class="v-snack v-snack--has-background v-snack--top" style="padding-bottom: 0px; padding-top: 123px;"><div class="v-snack__wrapper v-sheet theme--dark" style="display: none;"><div role="status" aria-live="polite" class="v-snack__content">

                </div><div class="v-snack__action "></div></div></div></div>
@stop
