<?php

$professional_qualifications = [
    ["id"=>"1","profession_id"=>"1","name"=>"Certificate in Ambulance Technician","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"2","profession_id"=>"3","name"=>"Diploma in Clinical Social Workers","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"3","profession_id"=>"3","name"=>"Degree in Clinical Social Workers","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"4","profession_id"=>"4","name"=>"Bachelor of Science in Counselling","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"5","profession_id"=>"4","name"=>"Bachelor of Science honors in Counselling","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"6","profession_id"=>"5","name"=>"Diploma in Systemic Family Counselling","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"7","profession_id"=>"5","name"=>"Diploma in Family therapy","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"8","profession_id"=>"5","name"=>"Diploma in HIV and AIDS Counselling care and Support","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"9","profession_id"=>"5","name"=>"Advanced Counselling course","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"10","profession_id"=>"5","name"=>"Certificate in Systemic Family therapy","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"11","profession_id"=>"5","name"=>"Advanced Diploma in Family Therapy","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"12","profession_id"=>"7","name"=>"Certificate Cardiographic Technique","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"13","profession_id"=>"7","name"=>"Diploma Electrocardiography Technology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"14","profession_id"=>"8","name"=>"Diploma Electroencephalographic Technology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"15","profession_id"=>"8","name"=>"Diploma Electroencephalographic Technology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"16","profession_id"=>"9","name"=>"Certificate in Emergency Medical Technician","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"17","profession_id"=>"10","name"=>"Bachelor of Science Degree in Health Education and Health Promotion","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"18","profession_id"=>"11","name"=>"National Diploma in Electronic Engineering (Communication Systems)","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"19","profession_id"=>"12","name"=>"Diploma in Hospital Food Services Supervisor","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"20","profession_id"=>"13","name"=>"Bachelor of Science Honours Degree in Applied Physics","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"21","profession_id"=>"13","name"=>"Master of Science Degree in Medical Physics","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"22","profession_id"=>"13","name"=>"Bachelor of Science Honours Degree in Physics","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"23","profession_id"=>"13","name"=>"Bachelor Of Science Applied Physics And Instrumentation Honours","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"24","profession_id"=>"15","name"=>"Bachelor of Science in Nutrition Degree","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"25","profession_id"=>"15","name"=>"Bachelor of Science Food Science and Nutrition Honours Degree","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"26","profession_id"=>"18","name"=>"Bachelor of Science Psychology Honours Degree","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"27","profession_id"=>"18","name"=>"Bachelor of Science Honours in Psychology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"28","profession_id"=>"18","name"=>"Bachelor of Science Special Honours in Psychology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"29","profession_id"=>"24","name"=>"Master of Science in Community Psychology Degree","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"30","profession_id"=>"18","name"=>"Bachelor of Science Honours Degree in Psychology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"31","profession_id"=>"18","name"=>"Master of Science Degree in Clinical Psychology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"32","profession_id"=>"18","name"=>"Bachelor of Social Sciences in Psychology (Honours)","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"33","profession_id"=>"20","name"=>"Bachelor of Science Honours Degree in Radiography (Diagnostic)","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"34","profession_id"=>"20","name"=>"Bachelor of Science Honours Degree in Radiography (Therapeutic)","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"35","profession_id"=>"20","name"=>"Diploma in Therapeutic Radiography (in association with the School of Radiography)","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"36","profession_id"=>"20","name"=>"Bachelor of Science (Honours) in Radiography","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"37","profession_id"=>"20","name"=>"Bachelors of Science (Special Honours) in Radiography","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"38","profession_id"=>"20","name"=>"Master of Science in Radiography","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"39","profession_id"=>"20","name"=>"Bachelor of Science Honours Degree in Radiography","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"40","profession_id"=>"22","name"=>"X-ray operators certificate","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"41","profession_id"=>"21","name"=>"Post Graduate Diploma in Medical Ultrasound","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"42","profession_id"=>"21","name"=>"Master of Science in Medical Ultrasonography","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"43","profession_id"=>"23","name"=>"Master of Science in Counselling","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"44","profession_id"=>"6","name"=>"Bachelor of Science in Dietetics","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"45","profession_id"=>"2","name"=>"Diploma in Clinical Medical Sciences","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"46","profession_id"=>"2","name"=>"Bachelor of Science in Physician Assistant","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"47","profession_id"=>"16","name"=>"Diploma Higher Education in Operating Department Practice","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"48","profession_id"=>"24","name"=>"Bachelor of Science Psychology Honours Degree","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"49","profession_id"=>"24","name"=>"Bachelor of Science Honours in Psychology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"50","profession_id"=>"24","name"=>"Bachelor of Science Special Honours in Psychology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"51","profession_id"=>"28","name"=>"Bachelor of Science Honours in Psychology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"52","profession_id"=>"28","name"=>"Bachelor of Science Honours in Psychology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"53","profession_id"=>"28","name"=>"Bachelor of Science Psychology Honours Degree","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"54","profession_id"=>"28","name"=>"Master of Science Degree in Occupational Psychology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"55","profession_id"=>"28","name"=>"Master of Science Degree in Industrial Psychology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"56","profession_id"=>"30","name"=>"Bachelor of Science Psychology Honours Degree","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"57","profession_id"=>"30","name"=>"Bachelor of Science Honours in Psychology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"58","profession_id"=>"30","name"=>"Master of Science in Counselling Psychology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"59","profession_id"=>"28","name"=>"Bachelor of Science Honours in Psychology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"60","profession_id"=>"28","name"=>"Bachelor of Science Psychology Honours Degree","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"61","profession_id"=>"30","name"=>"Bachelor of Science Special Honours in Psychology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"62","profession_id"=>"30","name"=>"Bachelor of Social Sciences in Psychology (Honours)","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"63","profession_id"=>"28","name"=>"Bachelor of Science Psychology Honours Degree","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"64","profession_id"=>"29","name"=>"Bachelor of Science Psychology Honours Degree","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"65","profession_id"=>"29","name"=>"Bachelor of Science Honours in Psychology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"66","profession_id"=>"29","name"=>"Bachelor of Science Special Honours in Psychology","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"67","profession_id"=>"29","name"=>"Bachelor of Social Sciences in Psychology (Honours)","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"68","profession_id"=>"33","name"=>"Bachelor of Science Honours in Radiography (Therapeutic)","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"69","profession_id"=>"33","name"=>"Diploma in Therapeutic Radiograpy","created_at"=>now(),"updated_at"=>now()],
    ["id"=>"70","profession_id"=>"21","name"=>"Post Graduate Diploma in Medical Ultrasonography","created_at"=>now(),"updated_at"=>now()],
];

return $professional_qualifications;
